version: 0.5.{build}
skip_tags: true
image: Visual Studio 2022
configuration:
- Release
- Debug
before_build:
  - appveyor-retry nuget restore
build:
  parallel: true
  verbosity: minimal
test:
  assemblies:
    only:
      - Figgle.Tests.dll
      - Figgle.Generator.Tests.dll
      - Figgle.Generator.AcceptanceTests.dll
test_script:
  - dotnet test .\Figgle.Tests\Figgle.Tests.csproj --no-build
  - dotnet test .\Figgle.Generator.Tests\Figgle.Generator.Tests.csproj --no-build
  - dotnet test .\Figgle.Generator.AcceptanceTests\Figgle.Generator.AcceptanceTests.csproj --no-build
