// Copyright Drew Noakes. Licensed under the Apache-2.0 license. See the LICENSE file for more details.

using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;

namespace Figgle.Fonts.Generator;

/// <summary>
/// This is an internal source generator that populates the FiggleFonts class with properties for each bundled font.
/// It is not intended for public use, but rather to automate the generation of the FiggleFonts class
/// </summary>
[Generator(LanguageNames.CSharp)]
internal sealed class FiggleFontGenerator : IIncrementalGenerator
{
    private static readonly string[] _newLineCharacters = ["\r\n", "\n"];

    private static readonly DiagnosticDescriptor _errorParsingFontFileDiagnostic = new(
        "FIGGLE_IMPL001",
        "Font Parsing Error",
        "Failed to parse font '{0}'. Ensure it is a valid FIGlet font file.",
        "FiggleFonts",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private const string Header =
        """
        // Copyright Drew Noakes. Licensed under the Apache-2.0 license. See the LICENSE file for more details.

        // <auto-generated>
        //     This code was generated by Figgle.Fonts.Generator.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>

        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var fontMemberNamesProvider = context.AdditionalTextsProvider
            .Where(file => Path.GetFileName(file.Path).Equals("Aliases.csv", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, cancellationToken) =>
            {
                var csvFileContent = file.GetText(cancellationToken)?.ToString();
                if (csvFileContent is null)
                {
                    return ImmutableArray<FontAlias>.Empty;
                }

                var aliases = ImmutableArray.CreateBuilder<FontAlias>();
                var entries = csvFileContent.Split(_newLineCharacters, StringSplitOptions.RemoveEmptyEntries);
                foreach (var entry in entries)
                {
                    var components = entry.Split(',');
                    if (components.Length == 2)
                    {
                        var fontName = components[0].Trim();
                        var memberName = components[1].Trim();
                        aliases.Add(new FontAlias(fontName, memberName));
                    }
                }

                return aliases.ToImmutable();
            });

        var parsedFontsProvider = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(".flf", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, cancellationToken) =>
            {
                var fontContent = file.GetText(cancellationToken)?.ToString();
                return new ParsedFont(
                    Path.GetFileNameWithoutExtension(file.Path),
                    fontContent is null ? null : FiggleFontParser.ParseString(fontContent));
            })
            .Collect();

        context.RegisterSourceOutput(fontMemberNamesProvider.Combine(parsedFontsProvider), (context, pair) =>
        {
            var memberByFontName = pair.Left.ToImmutableDictionary(
                keySelector: f => f.FontName,
                elementSelector: f => f.MemberName);
            var parsedFonts = pair.Right;

            foreach (var parsedFont in parsedFonts)
            {
                if (parsedFont.Font is null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        _errorParsingFontFileDiagnostic,
                        Location.None,
                        parsedFont.Name));
                }
            }

            var source = $$"""
                {{Header}}
                namespace Figgle.Fonts;

                partial class FiggleFonts
                {{{RenderFiggleFontProperties(memberByFontName, parsedFonts)}}
                }
                """;

            // we expect only a single Alias.csv file, so we don't need to worry about making
            // the source file name unique.
            context.AddSource("FiggleFonts.g.cs", source);

            static string RenderFiggleFontProperties(
                ImmutableDictionary<string, string> memberByFontName,
                ImmutableArray<ParsedFont> parsedFonts)
            {
                var builder = new StringBuilder(capacity: 4096);
                var indentation = new string(' ', 4);

                foreach (var parsedFont in parsedFonts.OrderBy(parsedFont => parsedFont.Name))
                {
                    if (!memberByFontName.TryGetValue(parsedFont.Name, out var memberName))
                    {
                        // Compose a PascalCased member name from the font name.
                        // Replace the first character, or any character after a space, dash, or underscore with an uppercase letter.
                        memberName = Regex.Replace(
                            parsedFont.Name,
                            """^(?<c>\w)|[\s_-]+(?<c>[\w0-9])""",
                            match => match.Groups["c"].Value.ToUpperInvariant());
                    }

                    builder.Append($$"""


                        {{indentation}}/// <summary>
                        {{indentation}}/// Obtains the <see cref="Figgle.FiggleFont" /> for the font name "{{parsedFont.Name}}".
                        {{indentation}}/// <example>
                        {{indentation}}/// <code>
                        {{indentation}}{{RenderSampleText(parsedFont.Name, parsedFont.Font, indentation)}}
                        {{indentation}}/// </code>
                        {{indentation}}/// </example>
                        {{indentation}}/// </summary>
                        {{indentation}}public static FiggleFont {{memberName}} => GetByName("{{parsedFont.Name}}");
                        """);
                }

                return builder.ToString();
            }

            static string RenderSampleText(string fontName, FiggleFont? font, string indentation)
            {
                if (font is null)
                {
                    return $"Failed to parse '{fontName}' into a {nameof(FiggleFont)}.";
                }

                var renderedText = font.Render(fontName);

                return string.Join(
                    $"\r\n{indentation}",
                    renderedText
                        .Split(_newLineCharacters, StringSplitOptions.None)
                        .Select(line => $"/// {EscapeXmlSpecialCharacters(line)}"));
            }

            static string EscapeXmlSpecialCharacters(string text)
            {
                // SecurityElement conveniently has Escape that escapes XML special
                // characters, so we can just reuse it.
                return SecurityElement.Escape(text);
            }
        });
    }

    private sealed record FontAlias(string FontName, string MemberName);

    private sealed record ParsedFont(string Name, FiggleFont? Font);
}
