// Auto-generated code - Do not modify manually
// Generated from FiggleFonts.Generated.tt

namespace Figgle.Fonts;

public static partial class FiggleFonts
{
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>1row</c>.</summary>
    public static FiggleFont OneRow => GetByName("1row");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>3-d</c>.</summary>
    public static FiggleFont ThreeD => GetByName("3-d");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>3d_diagonal</c>.</summary>
    public static FiggleFont ThreeDDiagonal => GetByName("3d_diagonal");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>3x5</c>.</summary>
    public static FiggleFont ThreeByFive => GetByName("3x5");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>4max</c>.</summary>
    public static FiggleFont FourMax => GetByName("4max");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>5lineoblique</c>.</summary>
    public static FiggleFont FiveLineOblique => GetByName("5lineoblique");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>acrobatic</c>.</summary>
    public static FiggleFont Acrobatic => GetByName("acrobatic");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>alligator</c>.</summary>
    public static FiggleFont Alligator => GetByName("alligator");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>alligator2</c>.</summary>
    public static FiggleFont Alligator2 => GetByName("alligator2");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>alligator3</c>.</summary>
    public static FiggleFont Alligator3 => GetByName("alligator3");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>alpha</c>.</summary>
    public static FiggleFont Alpha => GetByName("alpha");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>alphabet</c>.</summary>
    public static FiggleFont Alphabet => GetByName("alphabet");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>amc3line</c>.</summary>
    public static FiggleFont Amc3Line => GetByName("amc3line");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>amc3liv1</c>.</summary>
    public static FiggleFont Amc3Liv1 => GetByName("amc3liv1");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>amcaaa01</c>.</summary>
    public static FiggleFont AmcAaa01 => GetByName("amcaaa01");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>amcneko</c>.</summary>
    public static FiggleFont AmcNeko => GetByName("amcneko");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>amcrazo2</c>.</summary>
    public static FiggleFont AmcRazor2 => GetByName("amcrazo2");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>amcrazor</c>.</summary>
    public static FiggleFont AmcRazor => GetByName("amcrazor");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>amcslash</c>.</summary>
    public static FiggleFont AmcSlash => GetByName("amcslash");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>amcslder</c>.</summary>
    public static FiggleFont AmcSlder => GetByName("amcslder");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>amcthin</c>.</summary>
    public static FiggleFont AmcThin => GetByName("amcthin");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>amctubes</c>.</summary>
    public static FiggleFont AmcTubes => GetByName("amctubes");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>amcun1</c>.</summary>
    public static FiggleFont AmcUn1 => GetByName("amcun1");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>arrows</c>.</summary>
    public static FiggleFont Arrows => GetByName("arrows");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>ascii_new_roman</c>.</summary>
    public static FiggleFont AsciiNewRoman => GetByName("ascii_new_roman");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>avatar</c>.</summary>
    public static FiggleFont Avatar => GetByName("avatar");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>B1FF</c>.</summary>
    public static FiggleFont B1FF => GetByName("B1FF");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>banner</c>.</summary>
    public static FiggleFont Banner => GetByName("banner");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>banner3</c>.</summary>
    public static FiggleFont Banner3 => GetByName("banner3");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>banner3-D</c>.</summary>
    public static FiggleFont Banner3D => GetByName("banner3-D");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>banner4</c>.</summary>
    public static FiggleFont Banner4 => GetByName("banner4");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>barbwire</c>.</summary>
    public static FiggleFont BarbWire => GetByName("barbwire");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>basic</c>.</summary>
    public static FiggleFont Basic => GetByName("basic");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>bear</c>.</summary>
    public static FiggleFont Bear => GetByName("bear");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>bell</c>.</summary>
    public static FiggleFont Bell => GetByName("bell");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>benjamin</c>.</summary>
    public static FiggleFont Benjamin => GetByName("benjamin");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>big</c>.</summary>
    public static FiggleFont Big => GetByName("big");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>bigchief</c>.</summary>
    public static FiggleFont BigChief => GetByName("bigchief");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>bigfig</c>.</summary>
    public static FiggleFont BigFig => GetByName("bigfig");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>binary</c>.</summary>
    public static FiggleFont Binary => GetByName("binary");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>block</c>.</summary>
    public static FiggleFont Block => GetByName("block");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>blocks</c>.</summary>
    public static FiggleFont Blocks => GetByName("blocks");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>bolger</c>.</summary>
    public static FiggleFont Bolger => GetByName("bolger");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>braced</c>.</summary>
    public static FiggleFont Braced => GetByName("braced");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>bright</c>.</summary>
    public static FiggleFont Bright => GetByName("bright");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>broadway</c>.</summary>
    public static FiggleFont Broadway => GetByName("broadway");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>broadway_kb</c>.</summary>
    public static FiggleFont BroadwayKB => GetByName("broadway_kb");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>bubble</c>.</summary>
    public static FiggleFont Bubble => GetByName("bubble");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>bulbhead</c>.</summary>
    public static FiggleFont Bulbhead => GetByName("bulbhead");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>calgphy2</c>.</summary>
    public static FiggleFont Caligraphy2 => GetByName("calgphy2");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>caligraphy</c>.</summary>
    public static FiggleFont Caligraphy => GetByName("caligraphy");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>cards</c>.</summary>
    public static FiggleFont Cards => GetByName("cards");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>catwalk</c>.</summary>
    public static FiggleFont CatWalk => GetByName("catwalk");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>chiseled</c>.</summary>
    public static FiggleFont Chiseled => GetByName("chiseled");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>chunky</c>.</summary>
    public static FiggleFont Chunky => GetByName("chunky");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>coinstak</c>.</summary>
    public static FiggleFont Coinstak => GetByName("coinstak");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>cola</c>.</summary>
    public static FiggleFont Cola => GetByName("cola");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>colossal</c>.</summary>
    public static FiggleFont Colossal => GetByName("colossal");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>computer</c>.</summary>
    public static FiggleFont Computer => GetByName("computer");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>contessa</c>.</summary>
    public static FiggleFont Contessa => GetByName("contessa");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>contrast</c>.</summary>
    public static FiggleFont Contrast => GetByName("contrast");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>cosmic</c>.</summary>
    public static FiggleFont Cosmic => GetByName("cosmic");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>cosmike</c>.</summary>
    public static FiggleFont Cosmike => GetByName("cosmike");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>crawford</c>.</summary>
    public static FiggleFont Crawford => GetByName("crawford");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>crazy</c>.</summary>
    public static FiggleFont Crazy => GetByName("crazy");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>cricket</c>.</summary>
    public static FiggleFont Cricket => GetByName("cricket");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>cursive</c>.</summary>
    public static FiggleFont Cursive => GetByName("cursive");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>cyberlarge</c>.</summary>
    public static FiggleFont CyberLarge => GetByName("cyberlarge");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>cybermedium</c>.</summary>
    public static FiggleFont CyberMedium => GetByName("cybermedium");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>cybersmall</c>.</summary>
    public static FiggleFont CyberSmall => GetByName("cybersmall");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>cygnet</c>.</summary>
    public static FiggleFont Cygnet => GetByName("cygnet");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>DANC4</c>.</summary>
    public static FiggleFont DANC4 => GetByName("DANC4");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>dancingfont</c>.</summary>
    public static FiggleFont DancingFont => GetByName("dancingfont");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>decimal</c>.</summary>
    public static FiggleFont Decimal => GetByName("decimal");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>defleppard</c>.</summary>
    public static FiggleFont DefLeppard => GetByName("defleppard");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>diamond</c>.</summary>
    public static FiggleFont Diamond => GetByName("diamond");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>dietcola</c>.</summary>
    public static FiggleFont DietCola => GetByName("dietcola");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>digital</c>.</summary>
    public static FiggleFont Digital => GetByName("digital");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>doh</c>.</summary>
    public static FiggleFont Doh => GetByName("doh");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>doom</c>.</summary>
    public static FiggleFont Doom => GetByName("doom");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>dosrebel</c>.</summary>
    public static FiggleFont DosRebel => GetByName("dosrebel");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>dotmatrix</c>.</summary>
    public static FiggleFont DotMatrix => GetByName("dotmatrix");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>double</c>.</summary>
    public static FiggleFont Double => GetByName("double");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>doubleshorts</c>.</summary>
    public static FiggleFont DoubleShorts => GetByName("doubleshorts");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>drpepper</c>.</summary>
    public static FiggleFont DRPepper => GetByName("drpepper");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>dwhistled</c>.</summary>
    public static FiggleFont DWhistled => GetByName("dwhistled");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>eftichess</c>.</summary>
    public static FiggleFont EftiChess => GetByName("eftichess");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>eftifont</c>.</summary>
    public static FiggleFont EftiFont => GetByName("eftifont");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>eftipiti</c>.</summary>
    public static FiggleFont EftiPiti => GetByName("eftipiti");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>eftirobot</c>.</summary>
    public static FiggleFont EftiRobot => GetByName("eftirobot");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>eftitalic</c>.</summary>
    public static FiggleFont EftiItalic => GetByName("eftitalic");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>eftiwall</c>.</summary>
    public static FiggleFont EftiWall => GetByName("eftiwall");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>eftiwater</c>.</summary>
    public static FiggleFont EftiWater => GetByName("eftiwater");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>epic</c>.</summary>
    public static FiggleFont Epic => GetByName("epic");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>fender</c>.</summary>
    public static FiggleFont Fender => GetByName("fender");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>filter</c>.</summary>
    public static FiggleFont Filter => GetByName("filter");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>fire_font-k</c>.</summary>
    public static FiggleFont FireFontK => GetByName("fire_font-k");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>fire_font-s</c>.</summary>
    public static FiggleFont FireFontS => GetByName("fire_font-s");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>flipped</c>.</summary>
    public static FiggleFont Flipped => GetByName("flipped");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>flowerpower</c>.</summary>
    public static FiggleFont FlowerPower => GetByName("flowerpower");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>fourtops</c>.</summary>
    public static FiggleFont FourTops => GetByName("fourtops");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>fraktur</c>.</summary>
    public static FiggleFont Fraktur => GetByName("fraktur");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>funface</c>.</summary>
    public static FiggleFont FunFace => GetByName("funface");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>funfaces</c>.</summary>
    public static FiggleFont FunFaces => GetByName("funfaces");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>fuzzy</c>.</summary>
    public static FiggleFont Fuzzy => GetByName("fuzzy");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>georgi16</c>.</summary>
    public static FiggleFont Georgia16 => GetByName("georgi16");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>Georgia11</c>.</summary>
    public static FiggleFont Georgia11 => GetByName("Georgia11");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>ghost</c>.</summary>
    public static FiggleFont Ghost => GetByName("ghost");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>ghoulish</c>.</summary>
    public static FiggleFont Ghoulish => GetByName("ghoulish");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>glenyn</c>.</summary>
    public static FiggleFont Glenyn => GetByName("glenyn");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>goofy</c>.</summary>
    public static FiggleFont Goofy => GetByName("goofy");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>gothic</c>.</summary>
    public static FiggleFont Gothic => GetByName("gothic");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>graceful</c>.</summary>
    public static FiggleFont Graceful => GetByName("graceful");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>gradient</c>.</summary>
    public static FiggleFont Gradient => GetByName("gradient");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>graffiti</c>.</summary>
    public static FiggleFont Graffiti => GetByName("graffiti");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>greek</c>.</summary>
    public static FiggleFont Greek => GetByName("greek");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>heart_left</c>.</summary>
    public static FiggleFont HeartLeft => GetByName("heart_left");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>heart_right</c>.</summary>
    public static FiggleFont HeartRight => GetByName("heart_right");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>henry3d</c>.</summary>
    public static FiggleFont Henry3d => GetByName("henry3d");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>hex</c>.</summary>
    public static FiggleFont Hex => GetByName("hex");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>hieroglyphs</c>.</summary>
    public static FiggleFont Hieroglyphs => GetByName("hieroglyphs");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>hollywood</c>.</summary>
    public static FiggleFont Hollywood => GetByName("hollywood");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>horizontalleft</c>.</summary>
    public static FiggleFont HorizontalLeft => GetByName("horizontalleft");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>horizontalright</c>.</summary>
    public static FiggleFont HorizontalRight => GetByName("horizontalright");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>ICL-1900</c>.</summary>
    public static FiggleFont ICL1900 => GetByName("ICL-1900");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>impossible</c>.</summary>
    public static FiggleFont Impossible => GetByName("impossible");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>invita</c>.</summary>
    public static FiggleFont Invita => GetByName("invita");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>isometric1</c>.</summary>
    public static FiggleFont Isometric1 => GetByName("isometric1");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>isometric2</c>.</summary>
    public static FiggleFont Isometric2 => GetByName("isometric2");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>isometric3</c>.</summary>
    public static FiggleFont Isometric3 => GetByName("isometric3");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>isometric4</c>.</summary>
    public static FiggleFont Isometric4 => GetByName("isometric4");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>italic</c>.</summary>
    public static FiggleFont Italic => GetByName("italic");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>ivrit</c>.</summary>
    public static FiggleFont Ivrit => GetByName("ivrit");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>jacky</c>.</summary>
    public static FiggleFont Jacky => GetByName("jacky");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>jazmine</c>.</summary>
    public static FiggleFont Jazmine => GetByName("jazmine");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>jerusalem</c>.</summary>
    public static FiggleFont Jerusalem => GetByName("jerusalem");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>katakana</c>.</summary>
    public static FiggleFont Katakana => GetByName("katakana");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>kban</c>.</summary>
    public static FiggleFont Kban => GetByName("kban");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>keyboard</c>.</summary>
    public static FiggleFont Keyboard => GetByName("keyboard");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>knob</c>.</summary>
    public static FiggleFont Knob => GetByName("knob");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>konto</c>.</summary>
    public static FiggleFont Konto => GetByName("konto");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>kontoslant</c>.</summary>
    public static FiggleFont KontoSlant => GetByName("kontoslant");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>larry3d</c>.</summary>
    public static FiggleFont Larry3d => GetByName("larry3d");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>lcd</c>.</summary>
    public static FiggleFont Lcd => GetByName("lcd");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>lean</c>.</summary>
    public static FiggleFont Lean => GetByName("lean");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>letters</c>.</summary>
    public static FiggleFont Letters => GetByName("letters");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>lildevil</c>.</summary>
    public static FiggleFont LilDevil => GetByName("lildevil");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>lineblocks</c>.</summary>
    public static FiggleFont LineBlocks => GetByName("lineblocks");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>linux</c>.</summary>
    public static FiggleFont Linux => GetByName("linux");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>lockergnome</c>.</summary>
    public static FiggleFont LockerGnome => GetByName("lockergnome");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>madrid</c>.</summary>
    public static FiggleFont Madrid => GetByName("madrid");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>marquee</c>.</summary>
    public static FiggleFont Marquee => GetByName("marquee");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>maxfour</c>.</summary>
    public static FiggleFont MaxFour => GetByName("maxfour");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>merlin1</c>.</summary>
    public static FiggleFont Merlin1 => GetByName("merlin1");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>merlin2</c>.</summary>
    public static FiggleFont Merlin2 => GetByName("merlin2");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>mike</c>.</summary>
    public static FiggleFont Mike => GetByName("mike");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>mini</c>.</summary>
    public static FiggleFont Mini => GetByName("mini");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>mirror</c>.</summary>
    public static FiggleFont Mirror => GetByName("mirror");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>mnemonic</c>.</summary>
    public static FiggleFont Mnemonic => GetByName("mnemonic");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>modular</c>.</summary>
    public static FiggleFont Modular => GetByName("modular");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>morse</c>.</summary>
    public static FiggleFont Morse => GetByName("morse");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>morse2</c>.</summary>
    public static FiggleFont Morse2 => GetByName("morse2");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>moscow</c>.</summary>
    public static FiggleFont Moscow => GetByName("moscow");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>mshebrew210</c>.</summary>
    public static FiggleFont Mshebrew210 => GetByName("mshebrew210");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>muzzle</c>.</summary>
    public static FiggleFont Muzzle => GetByName("muzzle");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>nancyj</c>.</summary>
    public static FiggleFont NancyJ => GetByName("nancyj");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>nancyj-fancy</c>.</summary>
    public static FiggleFont NancyJFancy => GetByName("nancyj-fancy");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>nancyj-improved</c>.</summary>
    public static FiggleFont NancyJImproved => GetByName("nancyj-improved");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>nancyj-underlined</c>.</summary>
    public static FiggleFont NancyJUnderlined => GetByName("nancyj-underlined");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>nipples</c>.</summary>
    public static FiggleFont Nipples => GetByName("nipples");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>nscript</c>.</summary>
    public static FiggleFont NScript => GetByName("nscript");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>ntgreek</c>.</summary>
    public static FiggleFont NTGreek => GetByName("ntgreek");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>nvscript</c>.</summary>
    public static FiggleFont NVScript => GetByName("nvscript");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>o8</c>.</summary>
    public static FiggleFont O8 => GetByName("o8");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>octal</c>.</summary>
    public static FiggleFont Octal => GetByName("octal");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>ogre</c>.</summary>
    public static FiggleFont Ogre => GetByName("ogre");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>oldbanner</c>.</summary>
    public static FiggleFont OldBanner => GetByName("oldbanner");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>os2</c>.</summary>
    public static FiggleFont OS2 => GetByName("os2");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>pawp</c>.</summary>
    public static FiggleFont Pawp => GetByName("pawp");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>peaks</c>.</summary>
    public static FiggleFont Peaks => GetByName("peaks");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>peaksslant</c>.</summary>
    public static FiggleFont PeaksSlant => GetByName("peaksslant");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>pebbles</c>.</summary>
    public static FiggleFont Pebbles => GetByName("pebbles");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>pepper</c>.</summary>
    public static FiggleFont Pepper => GetByName("pepper");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>poison</c>.</summary>
    public static FiggleFont Poison => GetByName("poison");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>puffy</c>.</summary>
    public static FiggleFont Puffy => GetByName("puffy");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>puzzle</c>.</summary>
    public static FiggleFont Puzzle => GetByName("puzzle");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>pyramid</c>.</summary>
    public static FiggleFont Pyramid => GetByName("pyramid");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>rammstein</c>.</summary>
    public static FiggleFont Rammstein => GetByName("rammstein");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>rectangles</c>.</summary>
    public static FiggleFont Rectangles => GetByName("rectangles");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>red_phoenix</c>.</summary>
    public static FiggleFont RedPhoenix => GetByName("red_phoenix");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>relief</c>.</summary>
    public static FiggleFont Relief => GetByName("relief");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>relief2</c>.</summary>
    public static FiggleFont Relief2 => GetByName("relief2");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>rev</c>.</summary>
    public static FiggleFont Rev => GetByName("rev");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>reverse</c>.</summary>
    public static FiggleFont Reverse => GetByName("reverse");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>roman</c>.</summary>
    public static FiggleFont Roman => GetByName("roman");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>rot13</c>.</summary>
    public static FiggleFont Rot13 => GetByName("rot13");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>rotated</c>.</summary>
    public static FiggleFont Rotated => GetByName("rotated");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>rounded</c>.</summary>
    public static FiggleFont Rounded => GetByName("rounded");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>rowancap</c>.</summary>
    public static FiggleFont RowanCap => GetByName("rowancap");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>rozzo</c>.</summary>
    public static FiggleFont Rozzo => GetByName("rozzo");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>runic</c>.</summary>
    public static FiggleFont Runic => GetByName("runic");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>runyc</c>.</summary>
    public static FiggleFont Runyc => GetByName("runyc");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>santaclara</c>.</summary>
    public static FiggleFont SantaClara => GetByName("santaclara");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>sblood</c>.</summary>
    public static FiggleFont SBlood => GetByName("sblood");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>script</c>.</summary>
    public static FiggleFont Script => GetByName("script");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>serifcap</c>.</summary>
    public static FiggleFont SerifCap => GetByName("serifcap");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>shadow</c>.</summary>
    public static FiggleFont Shadow => GetByName("shadow");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>shimrod</c>.</summary>
    public static FiggleFont Shimrod => GetByName("shimrod");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>short</c>.</summary>
    public static FiggleFont Short => GetByName("short");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>slant</c>.</summary>
    public static FiggleFont Slant => GetByName("slant");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>slide</c>.</summary>
    public static FiggleFont Slide => GetByName("slide");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>slscript</c>.</summary>
    public static FiggleFont ScriptSlant => GetByName("slscript");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>small</c>.</summary>
    public static FiggleFont Small => GetByName("small");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>smallcaps</c>.</summary>
    public static FiggleFont SmallCaps => GetByName("smallcaps");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>smisome1</c>.</summary>
    public static FiggleFont IsometricSmall => GetByName("smisome1");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>smkeyboard</c>.</summary>
    public static FiggleFont KeyboardSmall => GetByName("smkeyboard");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>smpoison</c>.</summary>
    public static FiggleFont PoisonSmall => GetByName("smpoison");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>smscript</c>.</summary>
    public static FiggleFont ScriptSmall => GetByName("smscript");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>smshadow</c>.</summary>
    public static FiggleFont ShadowSmall => GetByName("smshadow");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>smslant</c>.</summary>
    public static FiggleFont SlantSmall => GetByName("smslant");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>smtengwar</c>.</summary>
    public static FiggleFont TengwarSmall => GetByName("smtengwar");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>soft</c>.</summary>
    public static FiggleFont Soft => GetByName("soft");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>speed</c>.</summary>
    public static FiggleFont Speed => GetByName("speed");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>spliff</c>.</summary>
    public static FiggleFont Spliff => GetByName("spliff");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>s-relief</c>.</summary>
    public static FiggleFont SRelief => GetByName("s-relief");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>stacey</c>.</summary>
    public static FiggleFont Stacey => GetByName("stacey");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>stampate</c>.</summary>
    public static FiggleFont Stampate => GetByName("stampate");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>stampatello</c>.</summary>
    public static FiggleFont Stampatello => GetByName("stampatello");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>standard</c>.</summary>
    public static FiggleFont Standard => GetByName("standard");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>starstrips</c>.</summary>
    public static FiggleFont Starstrips => GetByName("starstrips");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>starwars</c>.</summary>
    public static FiggleFont Starwars => GetByName("starwars");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>stellar</c>.</summary>
    public static FiggleFont Stellar => GetByName("stellar");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>stforek</c>.</summary>
    public static FiggleFont Stforek => GetByName("stforek");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>stop</c>.</summary>
    public static FiggleFont Stop => GetByName("stop");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>straight</c>.</summary>
    public static FiggleFont Straight => GetByName("straight");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>sub-zero</c>.</summary>
    public static FiggleFont SubZero => GetByName("sub-zero");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>swampland</c>.</summary>
    public static FiggleFont Swampland => GetByName("swampland");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>swan</c>.</summary>
    public static FiggleFont Swan => GetByName("swan");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>sweet</c>.</summary>
    public static FiggleFont Sweet => GetByName("sweet");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>tanja</c>.</summary>
    public static FiggleFont Tanja => GetByName("tanja");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>tengwar</c>.</summary>
    public static FiggleFont Tengwar => GetByName("tengwar");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>term</c>.</summary>
    public static FiggleFont Term => GetByName("term");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>test1</c>.</summary>
    public static FiggleFont Test1 => GetByName("test1");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>thick</c>.</summary>
    public static FiggleFont Thick => GetByName("thick");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>thin</c>.</summary>
    public static FiggleFont Thin => GetByName("thin");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>threepoint</c>.</summary>
    public static FiggleFont ThreePoint => GetByName("threepoint");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>ticks</c>.</summary>
    public static FiggleFont Ticks => GetByName("ticks");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>ticksslant</c>.</summary>
    public static FiggleFont TicksSlant => GetByName("ticksslant");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>tiles</c>.</summary>
    public static FiggleFont Tiles => GetByName("tiles");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>tinker-toy</c>.</summary>
    public static FiggleFont TinkerToy => GetByName("tinker-toy");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>tombstone</c>.</summary>
    public static FiggleFont Tombstone => GetByName("tombstone");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>train</c>.</summary>
    public static FiggleFont Train => GetByName("train");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>trek</c>.</summary>
    public static FiggleFont Trek => GetByName("trek");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>tsalagi</c>.</summary>
    public static FiggleFont Tsalagi => GetByName("tsalagi");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>tubular</c>.</summary>
    public static FiggleFont Tubular => GetByName("tubular");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>twisted</c>.</summary>
    public static FiggleFont Twisted => GetByName("twisted");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>twopoint</c>.</summary>
    public static FiggleFont TwoPoint => GetByName("twopoint");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>univers</c>.</summary>
    public static FiggleFont Univers => GetByName("univers");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>usaflag</c>.</summary>
    public static FiggleFont UsaFlag => GetByName("usaflag");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>varsity</c>.</summary>
    public static FiggleFont Varsity => GetByName("varsity");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>wavy</c>.</summary>
    public static FiggleFont Wavy => GetByName("wavy");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>weird</c>.</summary>
    public static FiggleFont Weird => GetByName("weird");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>wetletter</c>.</summary>
    public static FiggleFont WetLetter => GetByName("wetletter");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>whimsy</c>.</summary>
    public static FiggleFont Whimsy => GetByName("whimsy");
    /// <summary>Obtains the <see cref="FiggleFont"/> for the font named <c>wow</c>.</summary>
    public static FiggleFont Wow => GetByName("wow");
}

