name: CI

on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  ununtu:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore Figgle.sln

    - name: Build solution (Release)
      run: dotnet build Figgle.sln --configuration Release
    - name: Build solution (Debug)
      run: dotnet build Figgle.sln --configuration Debug

    - name: Test Figgle.Tests (Release)
      run: dotnet test --verbosity normal --configuration Release --no-build --framework net8.0 Figgle.Tests/Figgle.Tests.csproj
    - name: Test Figgle.Tests (Debug)
      run: dotnet test --verbosity normal --configuration Debug --no-build --framework net8.0 Figgle.Tests/Figgle.Tests.csproj

    - name: Test Figgle.Generator.Tests (Release)
      run: dotnet test --verbosity normal --configuration Release --no-build --framework net8.0 Figgle.Generator.Tests/Figgle.Generator.Tests.csproj
    - name: Test Figgle.Generator.Tests (Debug)
      run: dotnet test --verbosity normal --configuration Debug --no-build --framework net8.0 Figgle.Generator.Tests/Figgle.Generator.Tests.csproj

#    - name: Publish NativeAOT
#      run: dotnet publish --verbosity normal --configuration Release --framework net8.0 Figgle/Figgle.csproj

  windows:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore Figgle.sln

    - name: Build solution (Release)
      run: dotnet build Figgle.sln --configuration Release
    - name: Build solution (Debug)
      run: dotnet build Figgle.sln --configuration Debug

    - name: Test Figgle.Tests (Release)
      run: dotnet test --verbosity normal --configuration Release --no-build --framework net8.0 Figgle.Tests/Figgle.Tests.csproj
    - name: Test Figgle.Tests (Debug)
      run: dotnet test --verbosity normal --configuration Debug --no-build --framework net8.0 Figgle.Tests/Figgle.Tests.csproj

    - name: Test Figgle.Generator.Tests (Release)
      run: dotnet test --verbosity normal --configuration Release --no-build --framework net8.0 Figgle.Generator.Tests/Figgle.Generator.Tests.csproj
    - name: Test Figgle.Generator.Tests (Debug)
      run: dotnet test --verbosity normal --configuration Debug --no-build --framework net8.0 Figgle.Generator.Tests/Figgle.Generator.Tests.csproj

#    - name: Publish NativeAOT
#      run: dotnet publish --verbosity normal --configuration Release --framework net8.0 Figgle/Figgle.csproj
